### ISSUE TITLE
Initialize duckdb-dbt project

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/hcup-dbt#2]
This issue will document the initial set up of a dbt project with the duckdb adaptor. Note here some versions for quick references

 - Python:  3.10.5
 - DBT Core: 1.3.2
 - DBT duckdb plugin: 1.3.3

## Action items
- [x] set up python v3.10.5 with venv
   - [x] in VS-code command pallete `Python: Create Env` > `v3.10.5`
   - [x] activate Python venv
   - [x] Check python version `python which`
- [x] set up duckdb-dbt
   - [x]  `pip install dbt-duckdb`
   - [x] `pip freeze > requirements.txt` 
   - [x] `dbt init hcup` then move all dbt files to root directory
   - [x] setup first draft of `profiles.yml`. 

## Useful References:

- **Dbt set up documentation:** https://docs.getdbt.com/reference/warehouse-setups/duckdb-setup 
- **duckdb-dbt setup documentation:** https://github.com/jwills/dbt-duckdb#dbt-duckdb

**Comment by ran-codes** [comment]
## `profiles.yml`

Note our initial `profiles.yml` is shown below. Note that for now we just have two targets `dev` (pointing towards local machine) and `prod` pointing towards the encrypted server. 

```yml
hcup:
  outputs:
    dev:
      type: duckdb
      path: hcup-dev.duckdb
      extensions:
        - httpfs
        - parquet
      external_root: 'D:\git\hcup-dbt\external'
    prod:
      type: duckdb
      path: hcup-prod.duckdb
      extensions:
        - httpfs
        - parquet
      external_root: '\\files.drexel.edu\encrypted\SOPH\UHC\SchnakeMahl_HCUP\Database\Prototype\dbt-external-test\'
  target: dev
```
